### ISSUE TITLE
no such file or directory, open 'node_modules/serverless-offline-localstack/serverlessOfflineLocalstack.json'

### ISSUE THREAD

**Issue by rhushikesh** [lookinglass-in/serverless-offline-localstack#2]
While trying serverless offline start, it is not able to configure aws sdk with values

**Comment by ajagnanan** [comment]
it should be writing that file out during startup, code located here https://github.com/lookinglass-in/serverless-offline-localstack/blob/develop/src/localstack.js#L83. Can you try adding the `debug` option to see what the error is you're having?

**Comment by darbio** [comment]
I also get this error. Adding debug to the config makes no difference - there's no extra output.

serverless.yml
```
...

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-offline-localstack

custom:
  serverlessOfflineLocalstack:
    debug: true
```

Output:
```
192-168-1-102:serverless-api darbio $ sls offline start --stage local
Serverless: Configuring serverless offline -> localstack
Serverless: Configuring serverless offline -> kinesis consumer
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Watching typescript files...
Serverless: Starting Offline: local/us-east-1.

Serverless: Routes for jwt-authorizer:
Serverless: (none)

Serverless: Routes for api-v1-admin:
Serverless: GET /v1/admin
Serverless: Configuring Authorization: v1/admin/jwt-authorizer

Serverless: Offline listening on http://localhost:3000

Serverless: POST /v1/admin (λ: api-v1-admin)
Serverless: The first request might take a few extra seconds

{ Error: ENOENT: no such file or directory, open 'node_modules/serverless-offline-localstack/serverlessOfflineLocalstack.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.configureAWS (serverless-api/node_modules/serverless-offline-localstack/lib/localstack.js:248:31)
    at Function.configureAWS (serverless-api/node_modules/serverless-offline-localstack/lib/index.js:59:34)
    at new DynamoDb (serverless-api/.build/utils/db.js:49:41)
    at Object.<anonymous> (serverless-api/.build/functions/api/v1/website/get-started/handler.js:90:67)
    at step (serverless-api/.build/functions/api/v1/website/get-started/handler.js:32:23)
    at Object.next (serverless-api/.build/functions/api/v1/website/get-started/handler.js:13:53)
    at fulfilled (serverless-api/.build/functions/api/v1/website/get-started/handler.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/serverless-offline-localstack/serverlessOfflineLocalstack.json' }

Serverless: [500] {"statusCode":500,"body":"{\"message\":\"An error occurred\",\"error\":{\"errno\":-2,\"code\":\"ENOENT\",\"syscall\":\"open\",\"path\":\"node_modules/serverless-offline-localstack/serverlessOfflineLocalstack.json\"}}","headers":{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":true}}
(node:40086) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'node_modules/serverless-offline-localstack/serverlessOfflineLocalstack.json'
```

db.js (extract)
```
...
    if (Settings.Stage.toLowerCase() === 'local') {
      ServerlessOfflineLocalstack.configureAWS(AWS);
    }

    this.dynamo = new AWS.DynamoDB.DocumentClient();
...
```
